td:	testDriver.o intarr.o 
	gcc -o td testDriver.c intarr.c 
clean:	
	rm -f td *.o

gcc -Wall -std=c99 -o $@ main.c t1.c

$cd [directory name]
$make fractal
$./fractal

$cd 
$make 
$./td Hadfield.png
